import React from 'react';
import { Soup, Utensils, Coffee, Cake, Zap, Droplet } from 'lucide-react';

// ================= FULL MENU DATA =================
export const FULL_MENU_DATA = {
  noodles: {
    name: "Noodles",
    icon: <Utensils className="w-5 h-5 mr-2" />,
    items: [
      {
        id: 'n22',
        name: "Veg Japchae Noodles",
        price: "329",
        description: "Korean-styled glass noodles with colourful vegetables in a sweet-savory soy-based sauce.",
        image: "/menu/Veg Japchae Noodles.jpg",
        type: 'veg',
        ingredients: ["Glass Noodles", "Sweet Potato Noodles", "Vegetables"],
      },
      {
        id: 'n2',
        name: "Chicken Japchae Noodles",
        price: "359",
        description: "Korean-styled glass noodles with tender chicken and vegetables in a sweet-savory soy sauce.",
        image: "/menu/Chicken Japchae Noodles.jpg",
        type: 'nonveg',
        ingredients: ["Glass Noodles", "Chicken", "Vegetables"],
      },
      {
        id: 'n7',
        name: "Veg Jajangmyeon Noodles",
        price: "269",
        description: "Korean noodles smothered in a rich, savoury black bean sauce with vegetables.",
        image: "/menu/Veg Jajangmyeon Noodles.jpg",
        type: 'veg',
      },
      {
        id: 'n77',
        name: "Chicken Jajangmyeon Noodles",
        price: "299",
        description: "Korean noodles smothered in a rich, savoury black bean sauce with tender chicken.",
        image: "/menu/Chicken Jajangmyeon Noodles.jpg",
        type: 'nonveg',
      },
      {
        id: 'n1',
        name: "Pad Thai Noodles",
        price_veg: "255",
        price_nonveg: "285",
        description: "Wok-tossed noodles in a tangy tamarind sauce with veggies, peanuts, lime, and herbs.",
        image: "/menu/Veg Pad Thai Noodles.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 'n3',
        name: "WalkN Butter Chicken Noodles",
        price: "345",
        description: "Creamy butter chicken paired with spicy, garlicky noodles for a bold fusion of flavors.",
        image: "/menu/butter-chicken-noodles.jpg",
        type: 'nonveg',
      },
      {
        id: 'n4',
        name: "Chilli Crisp Noodles",
        price_veg: "259",
        price_nonveg: "289",
        description: "Wok-tossed noodles coated in a bold, spicy chilli oil with garlic, scallions, and crunchy bits.",
        image: "/menu/Chili Crisp Noodles.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 'n5',
        name: "Street Style Chowmein",
        price_veg: "219",
        price_nonveg: "249",
        description: "Noodles packed with colorful veggies, savory sauces, and a street-food twist for a bold flavor.",
        image: "/menu/chowmein.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 'n6',
        name: "Veg Teriyaki Noodles",
        price: "269",
        description: "Noodles tossed in a rich teriyaki sauce, complemented by fresh vegetables and a hint of sesame.",
        image: "/menu/Veg Terayaki Noodles.jpg",
        type: 'veg',
      },
      {
        id: 'n10',
        name: "Chicken Teriyaki Noodles",
        price: "299",
        description: "Noodles tossed in a rich teriyaki sauce with tender chicken and fresh vegetables.",
        image: "/menu/Veg Terayaki Noodles.jpg", 
        type: 'nonveg',
      },
      {
        id: 'n8',
        name: "Dan Dan Noodles",
        price_veg: "269",
        price_nonveg: "299",
        description: "Noodles tossed in a savoury sauce with aromatic chilli oil, seasonings and signature toppings.",
        image: "/menu/dan-dan-noodles.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 'n9',
        name: "WalkNoodles",
        price_veg: "269",
        price_nonveg: "299",
        description: "Our signature dish featuring perfectly cooked noodles in a rich, tangy sauce with sesame notes.",
        image: "/menu/WalkNoodles.jpg",
        type: 'veg_nonveg',
      }
    ],
  },
  ramen: {
    name: "Ramen",
    icon: <Soup className="w-5 h-5 mr-2" />,
    items: [
      {
        id: 'r11',
        name: "Veg Kimchi Ramen",
        price: "399",
        description: "Spicy, tangy kimchi meets rich, savory broth in this ultimate comfort bowl of ramen.",
        image: "/menu/Veg Kimchi Ramen.jpg",
        type: 'veg',
      },
      {
        id: 'r1',
        name: "Chicken Kimchi Ramen",
        price: "429",
        description: "Spicy, tangy kimchi meets rich, savory broth with tender chicken in every bite.",
        image: "/menu/Chicken Kimchi Ramen.jpg",
        type: 'nonveg',
      },
      {
        id: 'r22',
        name: "Veg Miso Ramen",
        price: "399",
        description: "Ramen with a rich miso broth, spiced to perfection, and topped with tender noodles and veggies.",
        image: "/menu/Veg Miso Ramen.jpg",
        type: 'veg',
      },
      {
        id: 'r2',
        name: "Chicken Miso Ramen",
        price: "429",
        description: "Ramen with a rich miso broth, tender chicken, and veggies with a hint of heat.",
        image: "/menu/Chicken Miso Ramen.jpg",
        type: 'nonveg',
      },
      {
        id: 'r3',
        name: "Veg Gochujang Ramen",
        price: "399",
        description: "Ramen noodles in a rich, flavorful broth, infused with the deep, tangy heat of Gochujang paste.",
        image: "/menu/Veg Gochujang Ramen.jpg",
        type: 'veg',
      },
      {
        id: 'r33',
        name: "Chicken Gochujang Ramen",
        price: "429",
        description: "Rich, tangy Gochujang broth with ramen noodles and succulent chicken.",
        image: "/menu/Chicken Gochujang Ramen.jpg",
        type: 'nonveg',
      },
      {
        id: 'r4',
        name: "Chilli Garlic Ramen",
        price_veg: "399",
        price_nonveg: "429",
        description: "Spicy and flavorful ramen with a bold chili garlic broth, tender noodles, and fresh toppings.",
        image: "/menu/Veg Chilli Garlic Ramen.jpg",
        type: 'veg_nonveg',
      },
    ],
  },
  small_plates: {
    name: "Small Plates",
    icon: <Zap className="w-5 h-5 mr-2" />,
    items: [
      {
        id: 's1',
        name: "Crispy Noodle Bhel",
        price: "159",
        description: "Crispy noodles, tangy chutneys, and fresh veggies for a wholesome twist on classic bhel.",
        image: "/menu/crispy-noodle-bhel.jpg",
        type: 'veg',
      },
      {
        id: 's14',
        name: "Korean Chili Garlic Potato",
        price: "229",
        description: "Soft, chewy mushroom-shaped potatoes tossed in aromatic garlic and chilies for a bold, savory bite.",
        image: "/menu/chilli-garlic-potato.jpg",
        type: 'veg',
      },
      {
        id: 's3',
        name: "Vietnamese Spring Roll",
        price_veg: "199",
        price_nonveg: "229",
        description: "Rice paper rolls packed with fresh veggies, herbs, and noodles, served with a tangy dipping sauce.",
        image: "/menu/vietnamese-spring-roll.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 's9',
        name: "Thai Basil Lettuce Bites",
        price_veg: "229",
        price_nonveg: "259",
        description: "Thai basil chicken/paneer wrapped in crisp lettuce for a fresh, flavorful, and healthy bite.",
        image: "/menu/Chicken Thai Basil Lettuce Bites.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 's5',
        name: "Spicy Gochujang Chicken Wings",
        price: "249",
        description: "Korean-style chicken wings tossed in a fiery gochujang glaze - sweet, smoky and spicy.",
        image: "/menu/gochujang-wings.jpg",
        type: 'nonveg',
      },
      {
        id: 's6',
        name: "Chicken Yakitori",
        price: "249",
        description: "Chicken skewers with spring onions glazed with a savory-sweet soy marinade, grilled to smoky perfection.",
        image: "/menu/yakitori.jpg",
        type: 'nonveg',
      },
      {
        id: 's15',
        name: "Crystal Veg Dimsum",
        price: "289",
        description: "Light translucent dimsums filled with seasonal vegetables bursting with authentic Asian flavours.",
        image: "/menu/Veg Dimsum.jpg",
        type: 'veg',
      },
      {
        id: 's7',
        name: "Cream Cheese Broccoli Dimsums",
        price: "349",
        description: "Creamy cheese blended with tender broccoli wrapped in a soft dimsum shell.",
        image: "/menu/Broccoli Cheese Dimsums.jpg",
        type: 'veg',
      },
      {
        id: 's11',
        name: "Thai Basil Chicken Dimsums",
        price: "349",
        description: "Authentic thai flavored chicken dimsum made with minced chicken, thai basil, chilli and lemongrass.",
        image: "/menu/Thai Basil Chicken Dimsum.jpg",
        type: 'nonveg',
      },
      {
        id: 's13',
        name: "Veggie Paneer Rice Paper Dumpling",
        price: "289",
        description: "Delicate rice paper parcels filled with a savory blend of spiced paneer, seasonal vegetables, and aromatic herbs.",
        image: "/menu/Veggie Paneer Dumpling.jpg",
        type: 'veg',
      },
      {
        id: 's8',
        name: "Chicken Rice Paper Dumpling",
        price: "349",
        description: "Delicious rice paper parcels filled with seasoned chicken, seasonal vegetables, and Asian herbs.",
        image: "/menu/Chicken Dumpling.jpg",
        type: 'nonveg',
      },
      {
        id: 's10',
        name: "Chili Garlic Potato",
        price: "229",
        description: "Crispy potatoes tossed in bold chili garlic sauce.",
        image: "/menu/Chili Garlic Potato.jpg",
        type: 'veg',
      },
      {
        id: 's4',
        name: "Basil Leaf Dim Sum",
        price: "229",
        description: "Steamed dumplings with basil & veggies.",
        image: "/menu/basil-dimsum.jpg",
        type: 'veg',
      }
    ],
  },
  broths: {
    name: "Broths",
    icon: <Droplet className="w-5 h-5 mr-2" />,
    items: [
      {
        id: 'b1',
        name: "Thukpa",
        price_veg: "219",
        price_nonveg: "249",
        description: "Himalayan noodle soup with wholesome veggies, warm spices, and comforting flavors.",
        image: "/menu/thukpa.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 'b2',
        name: "Coconut Thai Soup with Rice Noodles",
        price_veg: "299",
        price_nonveg: "329",
        description: "Thai soup with silky rice noodles, infused with coconut milk, lemongrass, and zesty lime.",
        image: "/menu/coconut-thai-soup.jpg",
        type: 'veg_nonveg',
      },
      {
        id: 'b3',
        name: "Kimchi Jjigae",
        price_veg: "249",
        price_nonveg: "279",
        description: "Korean-style spicy kimchi soup with tofu and veggies – bold in flavor, warm in soul.",
        image: "/menu/kimchi-jjigae.jpg",
        type: 'veg_nonveg',
      },
    ],
  },
  desserts: {
    name: "Desserts",
    icon: <Cake className="w-5 h-5 mr-2" />,
    items: [
      { id: 'd1', name: "Hong Kong Style Fruit Pancake", price: "189", description: "Pancake filled with fresh seasonal fruits, topped with whipped cream for a delightful treat.", image: "/menu/fruit-pancake.jpg", type: 'veg', },
      { id: 'd3', name: "Darsaan", price: "159", description: "Crispy honey-glazed flat noodle dessert served warm with a scoop of vanilla ice cream.", image: "/menu/dessert-bao.jpg", type: 'veg', },
      { id: 'd2', name: "Dessert Bao", price: "159", description: "Steamed bao stuffed with sweet filling.", image: "/menu/dessert-bao.jpg", type: 'veg' },
    ],
  },
  drinks: {
    name: "Drinks",
    icon: <Coffee className="w-5 h-5 mr-2" />,
    items: [
      { id: 'dr2', name: "Sparkling Fizz", price: "149", description: "Refreshing sparkling drink with seasonal fruit, zesty lime, and a fizzy twist.", image: "/menu/sparkling-fizz.jpg", type: 'veg' },
      { id: 'dr3', name: "Detoxify", price: "149", description: "Cucumber, mint, lemon & ginger - brewed and chilled for a clean, calming detox.", image: "/menu/detox-water.jpg", type: 'veg' },
      { id: 'dr4', name: "Lemonade", price: "149", description: "Zesty lemon meets cool mint for an ultra-refreshing burst.", image: "/menu/lemonade.jpg", type: 'veg' },
      { id: 'dr9', name: "Dalgona Cold Coffee", price: "159", description: "Frothy, fluffy coffee clouds floating over chilled milk and ice.", image: "/menu/vietnamese-coffee.jpg", type: 'veg' },
      { id: 'dr10', name: "Honey Iced Latte", price: "169", description: "Iced espresso layered with silky milk and pure honey for a naturally sweet finish.", image: "/menu/almond-coffee.jpg", type: 'veg' },
      { id: 'dr11', name: "Hojicha Iced Latte", price: "279", description: "Roasted hojicha tea served over ice with creamy milk and gently sweetened with honey.", image: "/menu/berry-tea.jpg", type: 'veg' },
      { id: 'dr1', name: "Too Berry Tea", price: "149", description: "Brewed berry tea with seasonal fruits.", image: "/menu/berry-tea.jpg", type: 'veg' },
      { id: 'dr5', name: "Vietnamese Cold Coffee", price: "149", description: "Chilled milk coffee with ice.", image: "/menu/vietnamese-coffee.jpg", type: 'veg' },
    ],
  },
};

export const CUSTOM_CHOICES = [
  { id: 'ch1', name: "Choice of Protein", list: ["Paneer", "Chicken", "Egg", "Cheese"] },
  { id: 'ch2', name: "Choice of Fibre", list: ["Bokchoy", "Mushrooms", "Broccoli", "Carrot", "Cabbage", "Baby corn", "Spinach", "Bell pepper"] },
  { id: 'ch3', name: "Choice of Noodles", list: ["Rice noodles", "Whole wheat", "Udon noodles", "Zoodles"] },
  { id: 'ch4', name: "Choice of Condiments", list: ["Fried garlic", "Spring onion", "Chilli garlic oil", "Nori sheet", "Crushed peanuts", "Thai chilli", "Sesame seed", "Chilli oil"] },
];

export const COMBO_ITEM = {
  id: 'cm1',
  name: "Combo Offer",
  description: "Choose Any Noodle + Any Small Plate + Any Drink",
  price_veg: "499",
  price_nonveg: "549",
};

export const CATEGORY_MAP = [
  { id: 'all', name: 'All Dishes', icon: <Utensils className="w-5 h-5 mr-2" /> },
  ...Object.keys(FULL_MENU_DATA).map(key => ({
    id: key,
    name: FULL_MENU_DATA[key].name, 
    icon: FULL_MENU_DATA[key].icon
  }))
];